### ISSUE TITLE
[C-01] Private key in plain sight in `.env`

### ISSUE THREAD

**Issue by vendrell46** [360yuno-stack/nexalo#1]
## Affected files
[`.env#L2`](https://github.com/360yuno-stack/nexalo/blob/main/.env#L2)

## Description
Sensitive information, including API keys and private keys, was found stored directly in environment variables. Such files (e.g., `.env`) must never be committed to version control as this exposes critical secrets to potential compromise.

## Impact
A malicious actor could retrieve the exposed private keys and use them to steal associated funds or access protected services.

## Recommendations
All keys (both private and API) should be rotated immediately to invalidate any potentially exposed credentials. Additionally, include the `.env` file in `.gitignore` to prevent it from being pushed to the repository in the future.

**Comment by vendrell46** [comment]
NOT FIXED

**Comment by vendrell46** [comment]
FIXED

**Comment by diazano** [comment]
⚠️ CORRECTION: NOT FIXED - .env File Still Public with Credentials

## Verification Status

After reviewing the current repository state, I must **correct the previous assessment**. This issue is **NOT FIXED**.

### ❌ Current State (Verified Today)

The `.env` file is **still present** in the main branch at:  
https://github.com/360yuno-stack/nexalo/blob/main/.env

### 🔴 Exposed Sensitive Data

The file currently contains (as of commit da7c925):

**Line 2:**
```
PRIVATE_KEY=bdd9e68ae435ca607715b0d4433e4578af65e4afb31277fb2c21140 6b5eebc9c
```

**Lines 5, 8-10, 13-14, 17-18:**
- `BSCSCAN_API_KEY` - API credentials  
- `VRF_SUBSCRIPTION_ID` - Chainlink credentials
- `VRF_COORDINATOR` - Chainlink address
- `KEY_HASH` - Chainlink key hash
- `FOUNDER_ADDRESS` - Wallet address
- `PARTNER_ADDRESS` - Wallet address  
- `USDT_ADDRESS` - Token address
- `WBTC_ADDRESS` - Token address

### 🔥 Critical Security Issues

**1. Private Key Exposure**  
The wallet private key on line 2 grants **full control** over the associated account. Anyone with access to this key can:
- Steal all funds from the wallet
- Sign arbitrary transactions  
- Impersonate the account owner

**2. API Key Exposure**  
The BSCScan API key enables unauthorized:
- Rate limit exhaustion
- Service abuse
- Account tracking

**3. Git History Persistence**  
Even if the file is removed now, it remains in **all historical commits**. The exposure is permanent.

### ❌ Missing Remediation Steps

The auditor's recommendations were **not followed**:

**1. Keys NOT Rotated**  
The private key and API keys need immediate rotation:
```bash
# Generate new private key
# Generate new BSCScan API key
# Update all deployments
```

**2. .gitignore NOT Updated**  
The `.env` file should be added to `.gitignore`:
```gitignore
# Add to .gitignore
.env
.env.local
.env.*.local
```

**3. File NOT Removed from History**  
Git history needs cleaning:
```bash
git filter-branch --force --index-filter \
  "git rm --cached --ignore-unmatch .env" \
  --prune-empty --tag-name-filter cat -- --all
```

### 📋 Required Actions

**Immediate (Critical):**
1. ✅ **Rotate private key immediately** - Generate new wallet  
2. ✅ **Rotate BSCScan API key** - Create new API key
3. ✅ **Rotate Chainlink VRF subscription** - Update coordinator
4. ✅ **Move ALL funds** from compromised wallet to new wallet

**Repository Cleanup:**
1. ❌ Add `.env` to `.gitignore` (not done)
2. ❌ Remove `.env` from repository (not done)
3. ❌ Clean `.env` from git history (not done)
4. ❌ Force push cleaned repository (not done)

**Operational:**
1. ❌ Update deployment scripts with new keys
2. ❌ Update environment variables in production
3. ❌ Document .env.example WITHOUT actual values

### 📝 Proper .env Management

**Create `.env.example`** (safe to commit):
```bash
# Wallet (NEVER commit actual private key!)
PRIVATE_KEY=your_private_key_here

# BSCScan
BSCSCAN_API_KEY=your_api_key_here

# Chainlink VRF BSC TESTNET
VRF_SUBSCRIPTION_ID=your_subscription_id
VRF_COORDINATOR=0x...
KEY_HASH=0x...

# Addresses
FOUNDER_ADDRESS=0x...
PARTNER_ADDRESS=0x...
```

**Update `.gitignore`:**
```gitignore
# Environment variables
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Never commit these!
**/private.key
**/*.pem
```

### Status Update

**Previous Assessment:** ✅ FIXED (incorrect)  
**Current Status:** ❌ **NOT FIXED**  
**Severity:** 🔴 **CRITICAL** - Active credential exposure  
**Risk Level:** 🚨 **MAXIMUM** - Funds can be stolen at any time

### Proof

File still accessible:  
- URL: https://github.com/360yuno-stack/nexalo/blob/main/.env  
- Line 2: Contains actual private key (66 hex characters)
- Commit: da7c925 (last month)
- Branch: main (public)

**This is an active security incident. All exposed credentials must be rotated immediately.**
